- name: Understanding precedence of variables
  hosts: all
  become: yes
  #vars:
  # USRNM: playuser
  # COMM: variable from playbook
  tasks: 
    - name: create a user
      user: 
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: USEROUT

    - debug:
       var: USEROUT.name
    - debug:
       var: USEROUT.comment

